# .github/workflows/go.yml
name: ğŸš€ Multi-Platform Build

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Application Name'
        required: true
        default: 'douyinlive'

env:
  DEFAULT_APP_NAME: 'douyinlive'  # é»˜è®¤åº”ç”¨åç§°

jobs:
  cross-build:
    name: ğŸ› ï¸ Build ${{ inputs.app_name || env.DEFAULT_APP_NAME }}
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ inputs.app_name || env.DEFAULT_APP_NAME }}
      BUILD_VERSION: ${{ github.run_id }}

    strategy:
      matrix:
        platform: 
          - { os: windows,  arch: amd64, ext: exe }
          - { os: linux,    arch: amd64, ext: '' }

    steps:
    - name: ğŸ” Checkout Code
      uses: actions/checkout@v4

    - name: ğŸš€ Build Binary
      shell: bash
      env:
        OUTPUT_FILE: ${{ env.APP_NAME }}-${{ env.BUILD_VERSION }}-${{ matrix.platform.os }}-${{ matrix.platform.arch }}${{ matrix.platform.ext }}
      run: |
        echo "Building: ${OUTPUT_FILE}"
        GOOS=${{ matrix.platform.os }} GOARCH=${{ matrix.platform.arch }} go build -o ${OUTPUT_FILE}
